trigger:
- '*'

stages:
- stage: "Build"
  jobs:
  # - job: "compile"
  #   steps:
  #     - task: Maven@4
  #       inputs:
  #         mavenPomFile: 'pom.xml'
  #         goals: 'compile'
  #         publishJUnitResults: false
  #         javaHomeOption: 'JDKVersion'
  #         mavenVersionOption: 'Default'
  #         mavenAuthenticateFeed: false
  #         effectivePomSkip: false

  # - job: "test"
  #   steps:
  #     - task: Maven@4
  #       inputs:
  #         mavenPomFile: 'pom.xml'
  #         goals: 'test'
  #         publishJUnitResults: true
  #         testResultsFiles: '**/surefire-reports/TEST-*.xml'
  #         testRunTitle: 'Unit Test'
  #         javaHomeOption: 'JDKVersion'
  #         mavenVersionOption: 'Default'
  #         mavenAuthenticateFeed: false
  #         effectivePomSkip: false
  #         pmdRunAnalysis: true
          
  - job: "package"
    steps:
      - task: Maven@4
        inputs:
          mavenPomFile: 'pom.xml'
          publishJUnitResults: false
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          goals: 'package'

  - job: "publish"
    dependsOn: package
    steps:
      - task: Maven@4
        inputs:
          mavenPomFile: 'pom.xml'
          publishJUnitResults: false
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: true
          effectivePomSkip: false
          goals: 'deploy'

      # - task: PublishBuildArtifacts@1
      #   inputs:
      #     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      #     ArtifactName: 'drop'
      #     publishLocation: 'Container'