trigger:
- '*'

stages:
- stage: "Build"
  jobs:
  - job: "Build"
    steps:
      - task: Maven@4
        inputs:
          mavenPomFile: 'pom.xml'
          goals: 'build'
          publishJUnitResults: false
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false

  - job: "test"
    steps:
      - task: Maven@4
        inputs:
          mavenPomFile: 'pom.xml'
          goals: 'test'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          testRunTitle: 'Unit Test'
          codeCoverageToolOption: 'Cobertura'
          codeCoverageFailIfEmpty: false
          codeCoverageRestoreOriginalPomXml: true
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: true
          sqMavenPluginVersionChoice: 'latest'
          pmdRunAnalysis: true
          
  - job: "package"
    steps:
      - task: Maven@4
        inputs:
          mavenPomFile: 'pom.xml'
          publishJUnitResults: false
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false
          goals: 'package'